version: build-{build}
max_jobs: 1
image: Visual Studio 2017
clone_folder: C:\prj\deca
build_script:
- cmd: >-
    SET

    SET PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%path%


    echo GET SUBMODULES

    cd C:\prj\deca

    echo git submodule init

    git config submodule.extern/HavokLib.url https://github.com/kk49/HavokLib.git

    git submodule update --init --recursive


    echo SETUP PYTHON

    cd C:\prj

    c:\Python37-x64\python --version

    c:\Python37-x64\python -m pip list

    c:\Python37-x64\python -m virtualenv venv

    venv\Scripts\activate

    python -m pip install "pip<19.0"

    pip list

    pip install -r deca/requirements.txt

    pip install pyinstaller

    pip install requests

    echo BUILD IMAGE DLL

    cd C:\prj\deca

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    cl.exe /D_USRDLL /D_WINDLL deca/process_image.c /link /DLL /OUT:process_image.dll


    echo BUILD HAVOK LIB

    cd C:\prj\deca\extern\HavokLib

    mkdir build

    cd build

    cmake --config Release -G "NMake Makefiles" ..\

    nmake

    mkdir _bin2xml

    cd _bin2xml

    cmake --config Release -G "NMake Makefiles" ..\..\_bin2xml\

    nmake


    echo PACKAGE

    cd C:\prj\deca

    pyinstaller deca_gui.spec --clean --noconfirm


after_build:
    cd dist\deca_gui

    7z a ..\..\deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip *

artifacts:
- path: deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip

deploy:
  artifact: deca_gui-b%APPVEYOR_BUILD_NUMBER%.zip
  prerelease: true
  description: 'Test Release'
  provider: GitHub
  auth_token:
    secure: fJVvaKg5+L0c1JRWMkuTHDvGKEU5xqjlCCI0vdQzN6M7uiTn54ZN0eJQ6Dx830HX
  on:
    # branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

on_success:
  - ps: cd C:\prj\deca
  - ps: python ./appveyor/on_success.py success CHANGELOG.md $env:BUILD_WEBHOOK_URL
